name : testGetHubActionsSchedule
on:
 schedule:
   - cron: '45 20 * * *'

jobs: 
  run-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2

    - name: run tests
      run: mvn test
      
